---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: labby
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      labby:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          labby:
            image:
              repository: ghcr.io/samuelloranger/labby
              tag: 1.4.0@sha256:208cf59c45920b3f10e39f9a75f63140f8f9296abbbf3a559019abe7a6bbd7d9
            env:
              TZ: America/Los_Angeles
              PORT: &port 8080
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
              readiness: *probe
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
    persistence:
      config:
        existingClaim: ${APP}
        globalMounts:
          - path: /app/config
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
    route:
      labby:
        hostnames:
          - "${APP_SUBDOMAIN:-${APP}}.kantai.xyz"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: labby
                port: *port
    service:
      labby:
        controller: labby
        ports:
          http:
            port: *port
