---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./opencode/ks.yaml
components:
  - ../../components/common
  - ../../components/litellm-key-push
  - ../../components/memini-key-push
  - ../../components/kopiur/secret
transformers:
  - ./transformers
