---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: pocket-id
  data:
    - secretKey: MAXMIND_LICENSE_KEY
      remoteRef:
        key: maxmind
        property: password
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pocket-id-keys
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: pocket-id-keys
  dataFrom:
    - extract:
        key: pocket-id-keys
