---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dashbrr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: dashbrr
  data:
    - secretKey: DASHBRR__OIDC_CLIENT_SECRET
      remoteRef:
        key: dashbrr-oidc
        property: client-secret
