---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashbrr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      dashbrr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          dashbrr:
            image:
              repository: ghcr.io/autobrr/dashbrr
              tag: v0.7.0@sha256:0a14f0b614e840e0157290d70abd753ea124a7af28769e79f11acbfc5db01cf0
            env:
              DASHBRR__DB_DSN: "postgres://dashbrr@pg18vc-rw.database.svc.cluster.local:5432/dashbrr?sslmode=verify-full&sslrootcert=/etc/postgresql/ca/ca.crt&sslcert=/etc/postgresql/client/tls.crt&sslkey=/etc/postgresql/client/tls.key"
              DASHBRR__DB_TYPE: postgres
              DASHBRR__LISTEN_ADDR: 0.0.0.0:8080
              DASHBRR__OIDC_CLIENT_ID: 66af8a8d-47e3-47d0-b3a3-f17a057f67f3
              DASHBRR__OIDC_ISSUER: https://pid.kantai.xyz
              DASHBRR__OIDC_REDIRECT_URL: https://${APP_SUBDOMAIN:-${APP}}.kantai.xyz/api/auth/oidc/callback
              TZ: America/Los_Angeles
            envFrom:
              - secretRef:
                  name: dashbrr
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8080
              readiness: *probe
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      data:
        type: emptyDir
        globalMounts:
          - path: /data
      pg-ca:
        type: configMap
        name: cluster-ca.crt
        globalMounts:
          - path: /etc/postgresql/ca
            readOnly: true
      pg-client:
        type: secret
        name: dashbrr-pg
        defaultMode: 0440
        globalMounts:
          - path: /etc/postgresql/client
            readOnly: true
    route:
      dashbrr:
        hostnames:
          - "${APP_SUBDOMAIN:-${APP}}.kantai.xyz"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - port: *port
                name: dashbrr
    service:
      dashbrr:
        controller: dashbrr
        ports:
          http:
            port: *port
