---
# yaml-language-server: $schema=https://crd.kantai.xyz/operator.victoriametrics.com/vmservicescrape_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: grafana-instance
spec:
  endpoints:
    - port: grafana
      path: /metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana-instance
