---
# yaml-language-server: $schema=https://crd.kantai.xyz/operator.victoriametrics.com/vmalertmanager_v1beta1.json
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: kantai
spec:
  configSelector:
    matchLabels:
      app.kubernetes.io/instance: kantai
  disableNamespaceMatcher: true
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: openebs-hostpath
        resources:
          requests:
            storage: 1Gi
