---
# yaml-language-server: $schema=https://crd.kantai.xyz/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name flatops-runner
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: gha-runner-scale-set
  values:
    githubConfigUrl: https://github.com/jfroy/flatops
    githubConfigSecret: flatops-runner-secret
    minRunners: 1
    maxRunners: 4
    containerMode:
      type: kubernetes
      kubernetesModeWorkVolumeClaim:
        accessModes:
          - ReadWriteOnce
        storageClassName: ceph-block
        resources:
          requests:
            storage: 10Gi
    controllerServiceAccount:
      name: actions-runner-controller
      namespace: actions-runner-system
    template:
      spec:
        runtimeClassName: kata
        securityContext:
          fsGroup: 1001
          fsGroupChangePolicy: OnRootMismatch
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
        containers:
          - name: runner
            image: ghcr.io/home-operations/actions-runner:2.335.1
            command:
              - /home/runner/run.sh
            env:
              - name: ACTIONS_RUNNER_REQUIRE_JOB_CONTAINER
                value: "false"
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
