---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      qbittorrent:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          qbittorrent:
            image:
              repository: ghcr.io/home-operations/qbittorrent
              tag: 5.2.3@sha256:4fcf15b7f265c2c8d7bc2a7e13240a07e0593c326f3cf3b5b9bb69eec5b79299
            env:
              TZ: America/Los_Angeles
              QBT_WEBUI_PORT: &port 80
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v2/app/version
                    port: *port
            securityContext: &securityContext
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
        initContainers:
          gluetun:
            image:
              repository: ghcr.io/jfroy/gluetun
              tag: v3.41.3@sha256:970fdef9eedb103e2f49a5c6716322d52053bc91fa67e6eebe32cfe43f315b50
            env:
              BLOCK_MALICIOUS: off # save 300MB of RAM; https://github.com/qdm12/gluetun/issues/2054
              DNS_CACHING: off
              DNS_SERVER: off
              DNS_UPSTREAM_IPV6: off
              DNS_UPSTREAM_PLAIN_ADDRESSES: 1.1.1.1:53,1.0.0.1:53
              DNS_UPSTREAM_RESOLVER_TYPE: plain
              FIREWALL_INPUT_PORTS: "80,9999"
              FIREWALL_IPTABLES_LOG_LEVEL: debug
              HEALTH_RESTART_VPN: off
              HEALTH_SERVER_ADDRESS: ":9999"
              LOG_LEVEL: debug
              PUBLICIP_API: cloudflare
              STORAGE_SERVERS_DIRECTORY_PATH: /gluetun/servers/
              TZ: America/Los_Angeles
              VERSION_INFORMATION: off
              VPN_INTERFACE: wg0
              VPN_TYPE: wireguard
            envFrom:
              - secretRef:
                  name: gluetun-qbittorrent-secret
            # https://github.com/qdm12/gluetun-wiki/blob/main/setup/advanced/kubernetes.md#adding-ipv6-rule--file-exists
            lifecycle:
              postStart:
                exec:
                  command:
                    - /bin/sh
                    - -c
                    - (ip rule del table 51820; ip -6 rule del table 51820) || true
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 9999
                  periodSeconds: 30
                  timeoutSeconds: 10
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: 9999
                  initialDelaySeconds: 10
                  timeoutSeconds: 10
                  failureThreshold: 12
            resources:
              limits:
                kernel.org/tun: 1
            restartPolicy: Always
            securityContext:
              <<: *securityContext
              capabilities: { add: ["NET_ADMIN", "NET_RAW"] }
              readOnlyRootFilesystem: false
              runAsNonRoot: false
              runAsUser: 0
          vuetorrent:
            image:
              repository: ghcr.io/jfroy/vuetorrent
              tag: 2.34.1@sha256:7fe6d12a1d0b39f291e4e06d31039149719d6944fa91c5eee3cfc783f7ff02cf
            command:
              - "/bin/sh"
              - "-c"
              - "ln -sf /proc/$$$$$$/root/vuetorrent /share/vuetorrent; touch /share/startup; sleep infinity"
            probes:
              startup:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - /bin/sh
                      - -c
                      - test -f /share/startup
                  periodSeconds: 1
            securityContext: *securityContext
            restartPolicy: Always
        pod:
          labels:
            pod-security.kantai.xyz/allow-added-capabilities: "true"
          hostname: qbittorrent
    defaultPodOptions:
      nodeSelector:
        kubernetes.io/hostname: kantai1
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [4000]
    persistence:
      config:
        existingClaim: ${APP}
        advancedMounts:
          qbittorrent:
            qbittorrent:
              - path: /config
      empty:
        type: emptyDir
        sizeLimit: 20Mi
        globalMounts:
          - path: /share
            subPath: share
          - path: /tmp
            subPath: tmp
      gluetun:
        existingClaim: gluetun-update
        advancedMounts:
          qbittorrent:
            gluetun:
              - path: /gluetun
                readOnly: true
      media:
        type: persistentVolumeClaim
        existingClaim: media1
        advancedMounts:
          qbittorrent:
            qbittorrent:
              - path: /media/qbittorrent
                subPath: qbittorrent
              - path: /media/sss
                subPath: sss
      media2:
        type: persistentVolumeClaim
        existingClaim: media2
        advancedMounts:
          qbittorrent:
            qbittorrent:
              - path: /media2/qbittorrent
                subPath: qbittorrent
      run:
        type: emptyDir
        medium: Memory
        sizeLimit: 10Mi
        globalMounts:
          - path: /run
          - path: /var/run
    service:
      qbittorrent:
        controller: qbittorrent
        type: ClusterIP
        ports:
          http:
            port: *port
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: qbittorrent
            patch: |
              - op: add
                path: /spec/template/spec/shareProcessNamespace
                value: true
