---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prowlarr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: prowlarr-secret
    template:
      data:
        PROWLARR__AUTH__APIKEY: "{{ .API_KEY }}"
        PROWLARR__POSTGRES__HOST: pg18vc-rw.database.svc.cluster.local
        PROWLARR__POSTGRES__MAINDB: prowlarr-main
        PROWLARR__POSTGRES__PASSWORD: "{{ .POSTGRES_PASSWORD }}"
        PROWLARR__POSTGRES__PORT: "5432"
        PROWLARR__POSTGRES__USER: prowlarr
  dataFrom:
    - extract:
        key: prowlarr
