---
# yaml-language-server: $schema=https://crd.kantai.xyz/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gpu-operator
spec:
  interval: 1h
  targetNamespace: gpu-operator
  chartRef:
    kind: OCIRepository
    name: gpu-operator
  install:
    disableOpenAPIValidation: true
  upgrade:
    disableOpenAPIValidation: true
  values:
    dcgmExporter:
      env:
        - name: KUBERNETES_VIRTUAL_GPUS
          value: "true"
      serviceMonitor:
        enabled: true
        honorLabels: true
        relabelings:
          - sourceLabels: ["__meta_kubernetes_pod_node_name"]
            regex: (.*)
            targetLabel: instance
            replacement: $1
            action: replace
    devicePlugin:
      config:
        name: time-slicing-config-all
        default: any
    driver:
      enabled: false
    hostPaths:
      driverInstallDir: /usr/local
    nfd:
      enabled: false
    toolkit:
      enabled: false
  postRenderers:
    - kustomize:
        patches:
          - target:
              group: apps
              version: v1
              kind: Deployment
              name: gpu-operator
            patch: |-
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: gpu-operator
              spec:
                template:
                  spec:
                    containers:
                      - name: gpu-operator
                        securityContext:
                          allowPrivilegeEscalation: false
                          capabilities: { drop: ["ALL"] }
                          readOnlyRootFilesystem: true
                          runAsNonRoot: true
                          runAsUser: 1000
                          runAsGroup: 1000
                    securityContext:
                      fsGroup: 1000
                      fsGroupChangePolicy: OnRootMismatch
