---
# yaml-language-server: $schema=https://crd.kantai.xyz/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openshell
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: openshell
  values:
    agentSandbox:
      preflight:
        enabled: false

    workload:
      kind: deployment
    replicaCount: 1

    server:
      externalDbSecret: openshell-pg

      disableTls: true
      tls:
        clientCaSecretName: ""

      oidc:
        issuer: https://pid.kantai.xyz
        audience: openshell-cli

      credentialStorage:
        existingSecret: openshell-cek

      workspaceStorageClass: ceph-block
      workspaceDefaultStorageSize: 20Gi

      telemetryEnabled: false
      logLevel: info

    grpcRoute:
      enabled: true
      gateway:
        create: false
        name: envoy-internal
        namespace: network
      hostnames:
        - openshell.kantai.xyz

    pkiInitJob:
      enabled: true
    certManager:
      enabled: false

    networkPolicy:
      enabled: true

  postRenderers:
    - kustomize:
        patches:
          - patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: openshell
              spec:
                template:
                  metadata:
                    annotations:
                      reloader.stakater.com/auto: "true"
          - patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: openshell
              spec:
                template:
                  spec:
                    containers:
                      - name: openshell-gateway
                        env:
                          - name: OPENSHELL_OIDC_ADMIN_ROLE
                            value: ""
                          - name: OPENSHELL_OIDC_USER_ROLE
                            value: ""
