---
# yaml-language-server: $schema=https://crd.kantai.xyz/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: openshell
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.1.1
    digest: sha256:32ba760e85225f68a4f7a1ed5133cd4d1e3d2bca7b4238633e94fd53f5c907f5
  url: oci://ghcr.io/nvidia/openshell/helm-chart
