---
# yaml-language-server: $schema=https://crd.kantai.xyz/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: csi-driver-smb
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: csi-driver-smb
