---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kite-pguser
spec:
  refreshInterval: "0"
  target:
    name: kite-pguser
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: kite
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
---
# yaml-language-server: $schema=https://crd.kantai.xyz/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: kite
spec:
  cluster:
    name: pg18vc
  name: kite
  login: true
  passwordSecret:
    name: kite-pguser
---
# yaml-language-server: $schema=https://crd.kantai.xyz/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: kite
spec:
  cluster:
    name: pg18vc
  name: kite
  owner: kite
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: kite
spec:
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
    - kind: SecretStore
      name: push-observability
  selector:
    secret:
      name: kite-pguser
  template:
    type: Opaque
    data:
      DB_DSN: "dbname=kite host=pg18vc-rw.database.svc.cluster.local password='{{ .password }}' sslmode=disable user=kite"
  dataTo:
    - storeRef:
        name: push-observability
      remoteKey: kite-pg
      match:
        regexp: "^(DB_DSN)$"
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec:
          targetMergePolicy: Ignore
