---
# yaml-language-server: $schema=https://crd.kantai.xyz/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: memini
spec:
  cluster:
    name: pg18vc
  name: memini
  login: true
  inRoles:
    - cert_login
  disablePassword: true
  clientCertificate: {}
---
# yaml-language-server: $schema=https://crd.kantai.xyz/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: memini
spec:
  cluster:
    name: pg18vc
  name: memini
  owner: memini
  extensions:
    - name: vector
    - name: vchord
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: memini
spec:
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
    - kind: SecretStore
      name: push-memini
  selector:
    secret:
      name: memini-client-cert
  dataTo:
    - storeRef:
        name: push-memini
      remoteKey: memini-pg
      match:
        regexp: "^(tls\\.crt|tls\\.key)$"
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec:
          targetMergePolicy: Ignore
