---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: readur-pguser
spec:
  refreshInterval: "0"
  target:
    name: readur-pguser
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: readur
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
---
# yaml-language-server: $schema=https://crd.kantai.xyz/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: readur
spec:
  cluster:
    name: pg18vc
  name: readur
  login: true
  passwordSecret:
    name: readur-pguser
---
# yaml-language-server: $schema=https://crd.kantai.xyz/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: readur
spec:
  cluster:
    name: pg18vc
  name: readur
  owner: readur
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: readur
spec:
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
    - kind: SecretStore
      name: push-default
  selector:
    secret:
      name: readur-pguser
  template:
    type: Opaque
    data:
      DATABASE_URL: "postgresql://readur:{{ .password }}@pg18vc-rw.database.svc.cluster.local:5432/readur"
  dataTo:
    - storeRef:
        name: push-default
      remoteKey: readur-pg
      match:
        regexp: "^(DATABASE_URL)$"
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec:
          targetMergePolicy: Ignore
