---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spoolman-pguser
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: spoolman-pguser
    template:
      type: kubernetes.io/basic-auth
      metadata:
        labels:
          cnpg.io/reload: "true"
      data:
        username: spoolman
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: spoolman
        property: DATABASE_PASSWORD
---
# yaml-language-server: $schema=https://crd.kantai.xyz/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: spoolman
spec:
  cluster:
    name: pg18vc
  name: spoolman
  login: true
  passwordSecret:
    name: spoolman-pguser
---
# yaml-language-server: $schema=https://crd.kantai.xyz/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: spoolman
spec:
  cluster:
    name: pg18vc
  name: spoolman
  owner: spoolman
