---
# yaml-language-server: $schema=https://crd.kantai.xyz/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: toolhive-registry-server
spec:
  cluster:
    name: pg18vc
  name: toolhive_registry_server
---
# yaml-language-server: $schema=https://crd.kantai.xyz/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: toolhive-registry
spec:
  cluster:
    name: pg18vc
  name: toolhive_registry
  login: true
  inRoles:
    - cert_login
    - toolhive_registry_server
  disablePassword: true
  clientCertificate: {}
---
# yaml-language-server: $schema=https://crd.kantai.xyz/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: toolhive-registry
spec:
  cluster:
    name: pg18vc
  name: toolhive_registry
  owner: toolhive_registry
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: toolhive-registry
spec:
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
    - kind: SecretStore
      name: push-toolhive-system
  selector:
    secret:
      name: toolhive-registry-client-cert
  dataTo:
    - storeRef:
        name: push-toolhive-system
      remoteKey: toolhive-registry-pg
      match:
        regexp: "^(tls\\.crt|tls\\.key)$"
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec:
          targetMergePolicy: Ignore
