---
# yaml-language-server: $schema=https://crd.kantai.xyz/trust.cert-manager.io/bundle_v1alpha1.json
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: cluster-ca.crt
spec:
  sources:
    - useDefaultCAs: true
    - secret:
        name: cluster-ca
        key: ca.crt
  target:
    configMap:
      key: ca.crt
---
apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: cluster-ca-certificates.crt
spec:
  sources:
    - useDefaultCAs: true
    - secret:
        name: cluster-ca
        key: ca.crt
  target:
    configMap:
      key: ca-certificates.crt
