---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: autobrr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: autobrr-secret
    template:
      data:
        AUTOBRR__DATABASE_TYPE: postgres
        AUTOBRR__POSTGRES_DATABASE: autobrr
        AUTOBRR__POSTGRES_HOST: pg18vc-rw.database.svc.cluster.local
        AUTOBRR__POSTGRES_PASS: "{{ .POSTGRES_PASSWORD }}"
        AUTOBRR__POSTGRES_PORT: "5432"
        AUTOBRR__POSTGRES_USER: autobrr
        AUTOBRR__SESSION_SECRET: "{{ .SESSION_SECRET }}"
  dataFrom:
    - extract:
        key: autobrr
