---
# yaml-language-server: $schema=https://crd.kantai.xyz/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: descheduler
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: descheduler
  values:
    kind: Deployment
    replicas: 2
    leaderElection:
      enabled: true
    cmdOptions:
      v: 4
    deschedulerPolicyAPIVersion: descheduler/v1alpha2
    deschedulerPolicy:
      metricsProviders:
        - source: KubernetesMetrics
      profiles:
        - name: default
          pluginConfig:
            - name: DefaultEvictor
              args:
                nodeFit: true
                podProtections:
                  defaultDisabled:
                    - "FailedBarePods"
                    - "PodsWithLocalStorage"
                    - "SystemCriticalPods"
            - name: RemoveFailedPods
              args:
                reasons:
                  - "ContainerStatusUnknown"
                  - "NodeAffinity"
                  - "NodeShutdown"
                  - "Terminated"
                  - "UnexpectedAdmissionError"
                includingInitContainers: true
                excludeOwnerKinds:
                  - "Job"
                minPodLifetimeSeconds: 1800
            - name: RemovePodsHavingTooManyRestarts
              args:
                podRestartThreshold: 100
                includingInitContainers: true
            - name: RemovePodsViolatingNodeAffinity
              args:
                nodeAffinityType:
                  - preferredDuringSchedulingIgnoredDuringExecution
                  - requiredDuringSchedulingIgnoredDuringExecution
            - name: RemovePodsViolatingNodeTaints
            - name: RemovePodsViolatingInterPodAntiAffinity
            - name: RemovePodsViolatingTopologySpreadConstraint
          plugins:
            balance:
              enabled:
                - RemovePodsViolatingTopologySpreadConstraint
            deschedule:
              enabled:
                - RemoveFailedPods
                - RemovePodsHavingTooManyRestarts
                - RemovePodsViolatingNodeTaints
                - RemovePodsViolatingNodeAffinity
                - RemovePodsViolatingInterPodAntiAffinity
    service:
      enabled: true
    serviceMonitor:
      enabled: true
