---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: spoolman
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: spoolman
    template:
      data:
        SPOOLMAN_DB_NAME: spoolman
        SPOOLMAN_DB_HOST: pg18vc-rw.database.svc.cluster.local
        SPOOLMAN_DB_PASSWORD: "{{ .DATABASE_PASSWORD }}"
        SPOOLMAN_DB_PORT: "5432"
        SPOOLMAN_DB_USERNAME: spoolman
  dataFrom:
    - extract:
        key: spoolman
