---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name renovate-operator
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
  dataFrom:
    - extract:
        key: renovate-operator
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name renovate-operator-s3
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: kubernetes
  target:
    name: *name
  data:
    - secretKey: access-key-id
      remoteRef:
        key: renovate-obc
        property: AWS_ACCESS_KEY_ID
    - secretKey: secret-access-key
      remoteRef:
        key: renovate-obc
        property: AWS_SECRET_ACCESS_KEY
