---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name renovate-operator-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        client-secret: "{{ .CLIENT_SECRET }}"
        session-secret: "{{ .SESSION_SECRET }}"
  dataFrom:
    - extract:
        key: github-jfroy-bot
