---
# yaml-language-server: $schema=https://crd.kantai.xyz/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: renovate-operator
  values:
    fullnameOverride: renovate-operator
    config:
      logStorage:
        mode: s3
    deployment:
      annotations:
        reloader.stakater.com/auto: "true"
    route:
      enabled: true
      hostnames:
        - renovate.kantai.xyz
      parentRefs:
        - name: envoy-internal
          namespace: network
    s3:
      bucket: renovate
      endpoint: http://rook-ceph-rgw-ceph-objectstore.rook-ceph.svc
      forcePathStyle: true
      existingSecret: renovate-operator-s3
    webhook:
      enabled: true
      route:
        enabled: true
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 401"]
        hostnames:
          - renovate-webhook.kantai.xyz
        parentRefs:
          - name: envoy-external
            namespace: network
    auth:
      oidc:
        enabled: true
        issuerUrl: https://pid.kantai.xyz
        clientId: bd4cdb27-ff5e-4fff-88a9-46409429e3e4
        existingSecret: renovate-operator
        secretKey: oidc-client-secret
        sessionSecretKey: session-key
        redirectUrl: https://renovate.kantai.xyz/auth/callback
    valkey:
      enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      dashboard:
        enabled: true
        grafanaDashboard:
          allowCrossNamespaceImport: true
    rbac:
      ownNamespaceOnly: true
