---
# yaml-language-server: $schema=https://crd.kantai.xyz/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: renovate-operator
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.12.2
  url: oci://ghcr.io/mogenius/helm-charts/renovate-operator
---
# yaml-language-server: $schema=https://crd.kantai.xyz/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: renovate-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: renovate-operator
  values:
    fullnameOverride: renovate-operator
    config:
      logStorage:
        mode: valkey
    deployment:
      annotations:
        reloader.stakater.com/auto: "true"
    route:
      enabled: true
      hostnames:
        - renovate.kantai.xyz
      parentRefs:
        - name: envoy-internal
          namespace: network
    webhook:
      enabled: true
      route:
        enabled: true
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 401"]
        hostnames:
          - renovate-webhook.kantai.xyz
        parentRefs:
          - name: envoy-external
            namespace: network
    auth:
      oidc:
        enabled: true
        issuerUrl: https://pid.kantai.xyz
        clientId: bd4cdb27-ff5e-4fff-88a9-46409429e3e4
        existingSecret: renovate-operator
        secretKey: oidc-client-secret
        sessionSecretKey: session-key
        redirectUrl: https://renovate.kantai.xyz/auth/callback
    valkey:
      enabled: true
      auth:
        enabled: false
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      dashboard:
        enabled: true
        grafanaDashboard:
          allowCrossNamespaceImport: true
    rbac:
      ownNamespaceOnly: true
