---
# https://github.com/containerd/containerd/pull/11131
apiVersion: v1alpha1
kind: CRICustomizationConfig
name: 30-buildkit
content: |-
  [plugins."io.containerd.cri.v1.runtime".containerd.runtimes.runc]
    cgroup_writable = true
---
apiVersion: v1alpha1
kind: CRICustomizationConfig
name: 30-cdi
content: |-
  [plugins."io.containerd.cri.v1.runtime"]
    enable_cdi = true
---
# https://spegel.dev/docs/getting-started/#talos
apiVersion: v1alpha1
kind: CRICustomizationConfig
name: 30-spegel
content: |-
  [plugins.'io.containerd.cri.v1.images']
    discard_unpacked_layers = false
---
# https://github.com/kubernetes/kubernetes/issues/102612
apiVersion: v1alpha1
kind: CRICustomizationConfig
name: 30-unprivileged
content: |-
  [plugins."io.containerd.cri.v1.runtime"]
    enable_unprivileged_ports = true
    enable_unprivileged_icmp = true
