---
# yaml-language-server: $schema=https://crd.kantai.xyz/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: toolhive-registry-server
spec:
  cluster:
    name: pg18vc
  name: toolhive_registry_server
---
# yaml-language-server: $schema=https://crd.kantai.xyz/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: toolhive-registry
spec:
  cluster:
    name: pg18vc
  name: toolhive_registry
  login: true
  inRoles:
    - cert_login
    - toolhive_registry_server
  disablePassword: true
  clientCertificate: {}
