---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: etampe
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: etampe
  data:
    - secretKey: CLOUDFLARE_ACCOUNT_ID
      remoteRef:
        key: cloudflare-email-sending/username
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: cloudflare-email-sending/credential
