---
# yaml-language-server: $schema=https://crd.kantai.xyz/postgresql.cnpg.io/database_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: radarr
spec:
  cluster:
    name: pg18vc
  name: radarr-main
  owner: radarr
