---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cleanrr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cleanrr-secret
    template:
      data:
        CLEANRR_SERVERS__RADARR__API_KEY: "{{ .RADARR_API_KEY }}"
        CLEANRR_SERVERS__SONARR__API_KEY: "{{ .SONARR_API_KEY }}"
  data:
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: radarr/API_KEY
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: sonarr/API_KEY
