---
# yaml-language-server: $schema=https://crd.kantai.xyz/toolhive.stacklok.dev/mcpoidcconfig_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: MCPOIDCConfig
metadata:
  name: ha-mcp
spec:
  type: inline
  inline:
    issuer: https://pid.kantai.xyz
    jwksAllowPrivateIP: true
