---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: litellm-vk-memini
spec:
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
    - kind: SecretStore
      name: push-memini
  selector:
    secret:
      name: litellm-vk-memini
  data:
    - match:
        secretKey: LITELLM_API_KEY
        remoteRef:
          remoteKey: memini-litellm
          property: MEMINI_EMBED_API_KEY
    - match:
        secretKey: LITELLM_API_KEY
        remoteRef:
          remoteKey: memini-litellm
          property: MEMINI_LLM_API_KEY
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: litellm-vk-opencode
spec:
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
    - kind: SecretStore
      name: push-opencode
  selector:
    secret:
      name: litellm-vk-opencode
  data:
    - match:
        secretKey: LITELLM_API_KEY
        remoteRef:
          remoteKey: opencode-litellm
          property: LITELLM_API_KEY
