---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/secretstore_v1.json
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: push-memini
spec:
  provider:
    kubernetes:
      remoteNamespace: memini
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: litellm-key-push
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/secretstore_v1.json
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: push-opencode
spec:
  provider:
    kubernetes:
      remoteNamespace: opencode
      server:
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: litellm-key-push
