---
connectivity:
  checker:
    target: 1.1.1.1:53
    interval: 1m
endpoints:
  - name: Cloudflare
    group: connectivity
    url: icmp://1.1.1.1
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
  - name: Google
    group: connectivity
    url: icmp://8.8.8.8
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
  - name: pg18vc
    group: services
    url: tcp://pg18vc-rw.database.svc.cluster.local:5432
    interval: 1m
    conditions:
      - "[CONNECTED] == true"
metrics: true
storage:
  type: sqlite
  path: ${GATUS_CONFIG_PATH}/gatus.db
  caching: true
ui:
  title: Status | Gatus
  header: Status
  logo: https://avatars.githubusercontent.com/u/49554
  link: https://github.com/jfroy
  buttons:
    - name: Github
      link: https://github.com/jfroy
    - name: Homelab
      link: https://github.com/jfroy/flatops
web:
  port: ${GATUS_WEB_PORT}
  read-buffer-size: 32768
