---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oxicloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: oxicloud
    template:
      data:
        OXICLOUD_OIDC_CLIENT_SECRET: "{{ .OIDC_CLIENT_SECRET }}"
  data:
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: oxicloud/OXICLOUD_OIDC_CLIENT_SECRET
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oxicloud-db
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: oxicloud-db
    template:
      data:
        OXICLOUD_DB_CONNECTION_STRING: "postgres://oxicloud:{{ .DB_PASSWORD }}@pg18vc-rw.database.svc.cluster.local:5432/oxicloud"
        # --
        INIT_POSTGRES_DBNAME: oxicloud
        INIT_POSTGRES_HOST: pg18vc-rw.database.svc.cluster.local
        INIT_POSTGRES_PASS: "{{ .DB_PASSWORD }}"
        INIT_POSTGRES_USER: oxicloud
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: "password"
            target: "DB_PASSWORD"
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oxicloud-initdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: oxicloud-initdb
  data:
    - secretKey: INIT_POSTGRES_SUPER_PASS
      remoteRef:
        key: cnpg-pg18vc/password
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: oxicloud-keys
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: oxicloud-keys
    template:
      data:
        OXICLOUD_JWT_SECRET: "{{ .JWT_SECRET }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: "password"
            target: "JWT_SECRET"
