---
# yaml-language-server: $schema=https://crd.kantai.xyz/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pg18vc
spec:
  secretName: pg18vc-tls
  duration: 168h
  renewBefore: 24h
  issuerRef:
    name: cluster-ca
    kind: ClusterIssuer
    group: cert-manager.io
  commonName: pg18vc-r.database.svc.cluster.local
  dnsNames:
    - pg18vc-r.database.svc.cluster.local
    - pg18vc-ro.database.svc.cluster.local
    - pg18vc-rw.database.svc.cluster.local
