---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trove
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: trove
  dataFrom:
    - extract:
        key: trove
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: trove-token
spec:
  refreshPolicy: CreatedOnce
  target:
    name: trove-token
    template:
      data:
        TROVE_BOOTSTRAP_TOKEN: &token "trove_{{ .TOKEN }}"
        TROVE_TOKEN: *token
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: "password"
            target: "TOKEN"
