---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/pushsecret_v1alpha1.json
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: openshell
spec:
  deletionPolicy: Delete
  refreshInterval: 1h
  secretStoreRefs:
    - kind: SecretStore
      name: push-openshell
  selector:
    secret:
      name: openshell-client-cert
  template:
    type: kubernetes.io/tls
    data:
      uri: "postgresql://openshell@pg18vc-rw.database.svc.cluster.local:5432/openshell?sslmode=verify-full&sslrootcert=/etc/postgresql/ca/ca.crt&sslcert=/etc/postgresql/client/tls.crt&sslkey=/etc/postgresql/client/tls.key"
  dataTo:
    - storeRef:
        name: push-openshell
      remoteKey: openshell-pg
      match:
        regexp: "^(tls\\.crt|tls\\.key|uri)$"
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec:
          targetMergePolicy: Ignore
