---
# yaml-language-server: $schema=https://crd.kantai.xyz/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: trust-manager
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.22.1
  url: oci://quay.io/jetstack/charts/trust-manager
---
# yaml-language-server: $schema=https://crd.kantai.xyz/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trust-manager
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: trust-manager
  values:
    app:
      metrics:
        service:
          servicemonitor:
            enabled: true
            interval: 1m
    crds:
      enabled: true
      keep: true
    defaultPackageImage:
      repository: quay.io/jetstack/trust-pkg-debian-bookworm
      tag: "20230311.0"
    secretTargets:
      enabled: true
      authorizedSecrets:
        - cluster-ca-secret
        - operator-ca-tls-cluster-ca
