---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: external-dns-cloudflare-secret
  data:
    - secretKey: api-token
      remoteRef:
        key: edns-cloudflare/credential
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-unifi
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: external-dns-unifi
  data:
    - secretKey: UNIFI_API_KEY
      remoteRef:
        key: unifi/credential
