---
# yaml-language-server: $schema=https://crd.kantai.xyz/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kopiur
spec:
  interval: 1h
  ref:
    branch: main
  url: https://github.com/home-operations/kopiur.git
