---
# yaml-language-server: $schema=https://crd.kantai.xyz/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kopiur
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 0.4.5
  url: oci://ghcr.io/home-operations/charts/kopiur
---
# yaml-language-server: $schema=https://crd.kantai.xyz/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kopiur
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kopiur
  values:
    grafanaDashboard:
      enabled: true
      grafanaOperator:
        enabled: true
        matchLabels:
          grafana.internal/instance: grafana
    installScope: cluster
    metrics:
      prometheusRule:
        enabled: true
      serviceMonitor:
        enabled: true
    secretProjection:
      enabled: true
    webhook:
      certManager:
        issuerRef:
          name: cluster-ca
          kind: ClusterIssuer
          group: cert-manager.io
      serviceMonitor:
        enabled: true
      tls:
        mode: cert-manager
