---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pinchflat
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      pinchflat:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          pinchflat:
            image:
              repository: ghcr.io/communitymaintained/pinchflat
              tag: 1.4.0@sha256:397222c1c3eb01bf9dc061162d1ae3c7b8a584a1dc8b24c151dbfb1b10708fdd
            env:
              LOG_LEVEL: info
              TZ: America/Los_Angeles
              UMASK: "022"
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthcheck
                    port: &port 8945
              readiness: *probe
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups: [4000]
    persistence:
      config:
        existingClaim: ${APP}
        globalMounts:
          - path: /config
      media:
        type: persistentVolumeClaim
        existingClaim: media2
        globalMounts:
          - path: /downloads
            subPath: library/youtube
      tmp:
        type: emptyDir
      yt-dlp:
        type: emptyDir
        globalMounts:
          - path: /etc/yt-dlp
    route:
      pinchflat:
        hostnames:
          - "${APP_SUBDOMAIN:-${APP}}.kantai.xyz"
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - name: pinchflat
                port: *port
    service:
      pinchflat:
        controller: pinchflat
        type: ClusterIP
        ports:
          http:
            port: *port
