---
# yaml-language-server: $schema=https://crd.kantai.xyz/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: silence-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: silence-operator
  values:
    alertmanagerAddress: http://vmalertmanager-kantai.observability.svc.cluster.local:9093
    networkPolicy:
      enabled: false
