---
# yaml-language-server: $schema=https://crd.kantai.xyz/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ngc-nvidia
spec:
  interval: 1h
  url: https://helm.ngc.nvidia.com/nvidia
