---
# yaml-language-server: $schema=https://crd.kantai.xyz/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app smartctl-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: prometheus-smartctl-exporter
  driftDetection:
    ignore:
      # Ignore "validated" annotation which is not inserted during install
      - paths: ["/metadata/annotations/prometheus-operator-validated"]
        target:
          kind: PrometheusRule
  values:
    fullnameOverride: *app
    image:
      repository: ghcr.io/home-operations/smartctl-exporter
      tag: 0.14.0@sha256:1ce54f6215b4e92ce600d292e6f88af100146521a8e54f449adf3c0f333a9571
    prometheusRules:
      enabled: false
    serviceMonitor:
      enabled: true
      relabelings:
        - sourceLabels: [__meta_kubernetes_pod_node_name]
          targetLabel: instance
