---
# yaml-language-server: $schema=https://crd.kantai.xyz/kopiur.home-operations.com/backupschedule_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: BackupSchedule
metadata:
  name: "${APP}"
spec:
  configRef:
    name: "${APP}"
  schedule:
    cron: "0 10 * * *"
    timezone: Etc/UTC
    concurrencyPolicy: Forbid
    runOnCreate: false
    suspend: false
