---
# yaml-language-server: $schema=https://crd.kantai.xyz/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: "${APP}"
spec:
  compression:
    compressor: zstd
    neverCompress: ["*.zip", "*.gz", "*.jpeg", "*.webp", "*.mp4"]
  copyMethod: Snapshot
  credentialProjection:
    enabled: true
  mover:
    inheritSecurityContextFrom:
      container: "${APP}"
      podSelector:
        matchLabels:
          app.kubernetes.io/name: "${APP}"
  repository:
    kind: ClusterRepository
    name: kopiur-r2
  retention:
    keepDaily: 7
    keepWeekly: 4
    keepMonthly: 12
  sources:
    - pvc:
        name: "${APP}"
  volumeSnapshotClassName: ceph-block
