---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zipline
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: zipline
  dataFrom:
    - extract:
        key: zipline
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zipline-keys
spec:
  refreshInterval: "0"
  target:
    name: zipline-keys
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: "password"
            target: "CORE_SECRET"
