---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: livesync
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: livesync
    template:
      data:
        COUCHDB_USER: admin
        COUCHDB_PASSWORD: "{{ .COUCHDB_PASSWORD }}"
        COUCHDB_SECRET: "{{ .COUCHDB_SECRET }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: "password"
            target: "COUCHDB_PASSWORD"
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: "password"
            target: "COUCHDB_SECRET"
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: livesync-sync
spec:
  refreshInterval: "0"
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: livesync-sync
    template:
      data:
        SYNC_USER: sync
        SYNC_PASSWORD: "{{ .SYNC_PASSWORD }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: "password"
            target: "SYNC_PASSWORD"
