# yaml-language-server: $schema=https://crd.kantai.xyz/objectbucket.io/objectbucketclaim_v1alpha1.json
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: plane-obc
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  bucketName: plane
  storageClassName: ceph-bucket
