---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name github-jfroy-bot-private-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        private_key_pem: "{{ .PRIVATE_KEY }}"
  dataFrom:
    - extract:
        key: github-jfroy-bot
---
# yaml-language-server: $schema=https://crd.kantai.xyz/generators.external-secrets.io/githubaccesstoken_v1alpha1.json
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: github-jfroy-bot-auth-token
spec:
  appID: Iv23li6vvjqdgaiJgDNU
  installID: "50278892"
  auth:
    privateKey:
      secretRef:
        name: github-jfroy-bot-private-key
        key: private_key_pem
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name github-jfroy-bot-auth-token
spec:
  refreshInterval: 30m
  target:
    name: *name
    template:
      data:
        RENOVATE_TOKEN: "{{ .token }}"
        GITHUB_COM_TOKEN: "{{ .token }}"
        GITHUB_COM_USER: jfroy-bot
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: github-jfroy-bot-auth-token
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name docker-hub-token
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: *name
    template:
      data:
        DOCKERHUB_USERNAME: jfroy
        DOCKERHUB_TOKEN: "{{ .credential }}"
  dataFrom:
    - extract:
        key: dockerhub-renovate
