---
# yaml-language-server: $schema=https://crd.kantai.xyz/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: github-jfroy-bot
spec:
  provider:
    name: github
  discoveryFilters:
  - jfroy/*
  skipForks: true
  githubAppReference:
    secretName: github-jfroy-bot-app
    appIdSecretKey: APP_ID
    installationIdSecretKey: INSTALL_ID
    pemSecretKey: PEM
  # renovate: datasource=docker depName=ghcr.io/jfroy/renovate
  image: ghcr.io/jfroy/renovate:44.50.2@sha256:6af30455dff3bf92a3dda00e737abe12edd2644aae97c437ce4a9461a3f7024a
  schedule: 0,30 * * * *
  parallelism: 10
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 1Gi
  runtimeClassName: kata
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: webhook-token
        key: token
    sync:
      enabled: true
  renovateConfig:
    inline: |
      module.exports = {
        allowedCommands: ['^helm-docs( .*)?$', '^helm-schema( .*)?$'],
        allowedUnsafeExecutions: ['mise'],
        platformCommit: 'enabled',
        hostRules: [
          {
            hostType: 'docker',
            matchHost: 'docker.io',
            username: process.env.DOCKERHUB_USERNAME,
            password: process.env.DOCKERHUB_TOKEN,
          },
        ],
      };
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: DOCKERHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: docker-hub-token
          key: DOCKERHUB_USERNAME
    - name: DOCKERHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: docker-hub-token
          key: DOCKERHUB_TOKEN
