---
# yaml-language-server: $schema=https://crd.kantai.xyz/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: github-jfroy-bot
spec:
  provider:
    name: github
  discoveryFilters:
  - jfroy/*
  skipForks: true
  githubAppReference:
    secretName: github-jfroy-bot-app
    appIdSecretKey: APP_ID
    installationIdSecretKey: INSTALL_ID
    pemSecretKey: PEM
  # renovate: datasource=docker depName=ghcr.io/jfroy/renovate
  image: ghcr.io/jfroy/renovate:44.108.1@sha256:c42fa05bde495660f33d2c77e327372ede749ca0204726c4a573f4cd6ab0f44b
  schedule: 0,30 * * * *
  parallelism: 10
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 1Gi
  runtimeClassName: kata
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: webhook-token
        key: token
    sync:
      enabled: true
  renovateConfig:
    inline: |
      module.exports = {
        allowedCommands: ['^helm-docs( .*)?$', '^helm-schema( .*)?$'],
        allowedUnsafeExecutions: ['mise'],
        platformCommit: 'enabled',
        internalHostAccess: 'block',
        hostRules: [
          {
            hostType: 'docker',
            matchHost: 'docker.io',
            username: process.env.DOCKERHUB_USERNAME,
            password: process.env.DOCKERHUB_TOKEN,
          },
          { matchHost: 'kantai.xyz' },
          { matchHost: 'etincelle.cloud' },
        ],
      };
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: DOCKERHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: docker-hub-token
          key: DOCKERHUB_USERNAME
    - name: DOCKERHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: docker-hub-token
          key: DOCKERHUB_TOKEN
