---
# yaml-language-server: $schema=https://crd.kantai.xyz/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: github-jfroy-bot
spec:
  provider:
    name: github
  discoveryFilters:
  - jfroy/*
  skipForks: true
  secretRef: github-jfroy-bot-auth-token
  # renovate: datasource=docker depName=ghcr.io/jfroy/renovate
  image: ghcr.io/jfroy/renovate:43.256.2@sha256:5f8a7de17ef0595b1f8867e05d583cad187ea461cdd1dff2a2648ac9913c7168
  schedule: 0,30 * * * *
  parallelism: 10
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      memory: 1Gi
  runtimeClassName: kata
  webhook:
    enabled: true
    authentication:
      enabled: true
      secretRef:
        name: webhook-token
        key: token
    sync:
      enabled: true
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: >-
        [
          "^helm-docs( .*)?$",
          "^helm-schema( .*)?$"
        ]
    - name: RENOVATE_ALLOWED_UNSAFE_EXECUTIONS
      value: "mise"
    - name: RENOVATE_PLATFORM_COMMIT
      value: enabled
    - name: DOCKERHUB_USERNAME
      valueFrom:
        secretKeyRef:
          name: docker-hub-token
          key: DOCKERHUB_USERNAME
    - name: DOCKERHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: docker-hub-token
          key: DOCKERHUB_TOKEN
    - name: RENOVATE_HOST_RULES
      value: >-
        [
          {
            "hostType": "docker",
            "matchHost": "docker.io",
            "username": "$(DOCKERHUB_USERNAME)",
            "password": "$(DOCKERHUB_TOKEN)"
          }
        ]
