---
# yaml-language-server: $schema=https://crd.kantai.xyz/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seerr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: seerr-chart
  values:
    fullnameOverride: seerr
    podAnnotations:
      reloader.stakater.com/auto: "true"
    securityContext:
      readOnlyRootFilesystem: true
    extraEnv:
      - name: DB_HOST
        value: pg18vc-rw.database.svc.cluster.local
      - name: DB_NAME
        value: seerr
      - name: DB_PORT
        value: "5432"
      - name: DB_SSL_CA_FILE
        value: /etc/postgresql/ca/ca.crt
      - name: DB_SSL_CERT_FILE
        value: /etc/postgresql/client/tls.crt
      - name: DB_SSL_KEY_FILE
        value: /etc/postgresql/client/tls.key
      - name: DB_TYPE
        value: postgres
      - name: DB_USE_SSL
        value: "true"
      - name: DB_USER
        value: seerr
      - name: TZ
        value: America/Los_Angeles
    extraEnvFrom:
      - secretRef:
          name: seerr
    config:
      persistence:
        existingClaim: seerr
    volumes:
      - name: logs
        emptyDir:
          sizeLimit: 256Mi
      - name: next-cache
        emptyDir:
          sizeLimit: 1Gi
      - name: tmp
        emptyDir:
          medium: Memory
          sizeLimit: 128Mi
      - name: pg-ca
        configMap:
          name: cluster-ca.crt
      - name: pg-client
        secret:
          secretName: seerr-pg
          defaultMode: 0440
    volumeMounts:
      - name: logs
        mountPath: /app/config/logs
      - name: next-cache
        mountPath: /app/.next/cache
      - name: tmp
        mountPath: /tmp
      - name: pg-ca
        mountPath: /etc/postgresql/ca
        readOnly: true
      - name: pg-client
        mountPath: /etc/postgresql/client
        readOnly: true
    route:
      main:
        enabled: true
        parentRefs:
          - name: envoy-internal
            namespace: network
        hostnames:
          - seerr.kantai.xyz
