---
# yaml-language-server: $schema=https://crd.kantai.xyz/postgresql.cnpg.io/databaserole_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: miniflux
spec:
  cluster:
    name: pg18vc
  name: miniflux
  login: true
  inRoles:
    - cert_login
  disablePassword: true
  clientCertificate: {}
