---
apiVersion: v1alpha1
kind: UnattendedInstallConfig
provisioning:
  diskSelector:
    match: disk.wwid == "eui.e8238fa6bf530001001b448b4a49b465"
---
apiVersion: v1alpha1
kind: KubeNodeConfig
labels:
  secureboot.kantai.xyz: "true"
  node.kantai.xyz/high-cpu: "true"
  node.kubernetes.io/exclude-from-external-load-balancers:
    $patch: delete
taints:
  node-role.kubernetes.io/control-plane:
    $patch: delete
---
apiVersion: v1alpha1
kind: SysctlConfig
params:
  net.core.bpf_jit_harden: "1"
  net.ipv6.conf.all.accept_ra: "2"
  net.ipv6.conf.all.forwarding: "1"
  net.ipv6.conf.enp1s0f0np0.accept_ra: "2"
  net.ipv6.conf.enp1s0f0np0.forwarding: "1"
