---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homebox
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: homebox
  dataFrom:
    - extract:
        key: homebox
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homebox-keys
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: openbao
  target:
    name: homebox-keys
  dataFrom:
    - extract:
        key: homebox-keys
