---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: browserr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: browserr
  data:
    - secretKey: SEERR_API_KEY
      remoteRef:
        key: seerr/API_KEY
    - secretKey: TMDB_ACCESS_TOKEN
      remoteRef:
        key: tmdb/token
---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: browserr-keys
spec:
  refreshInterval: "0"
  target:
    name: browserr-keys
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: password
            target: SESSION_SECRET
