---
# yaml-language-server: $schema=https://crd.kantai.xyz/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app edns-unifi-crd
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: external-dns
  values:
    fullnameOverride: *app
    extraArgs:
      - --crd-source-apiversion=externaldns.k8s.io/v1alpha1
      - --crd-source-kind=DNSEndpoint
      - --label-filter=external-dns.kantai.xyz/unifi
    logLevel: debug
    podAnnotations:
      secret.reloader.stakater.com/reload: external-dns-unifi
    policy: sync
    serviceMonitor:
      enabled: true
    sources: ["crd"]
    triggerLoopOnEvent: true
    txtOwnerId: unifi-crd
    txtPrefix: edns.
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/home-operations/external-dns-unifi-webhook
          tag: 0.10.6@sha256:b35a7aac743ddbf7edff3266d8b0b0ac108dc0d56d692b322e51ec99f57b34c5
        env:
          - name: UNIFI_HOST
            value: https://unifi.internal
          - name: UNIFI_API_KEY
            valueFrom:
              secretKeyRef:
                name: external-dns-unifi
                key: UNIFI_API_KEY
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
