---
# yaml-language-server: $schema=https://crd.kantai.xyz/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: zot
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: zot
  values:
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
      fsGroupChangePolicy: OnRootMismatch
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
    env:
      - name: TZ
        value: America/Los_Angeles
    service:
      type: ClusterIP
      port: 5000
    httproute:
      enabled: true
      parentRefs:
        - name: envoy-internal
          namespace: network
      hostnames:
        - "registry.kantai.xyz"
    persistence: true
    pvc:
      create: true
      storage: 100Gi
      storageClassName: ceph-block
    mountConfig: true
    configFiles:
      config.json: |-
        {
          "distSpecVersion": "1.1.0",
          "storage": {
            "rootDirectory": "/var/lib/registry",
            "gc": true,
            "gcDelay": "1h",
            "gcInterval": "6h"
          },
          "http": {
            "address": "0.0.0.0",
            "port": "5000"
          },
          "log": {
            "level": "info"
          },
          "extensions": {
            "metrics": {
              "enable": true,
              "prometheus": {
                "path": "/metrics"
              }
            },
            "search": {
              "enable": true
            },
            "ui": {
              "enable": true
            }
          }
        }
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
        interval: 1m
        path: /metrics
    extraVolumes:
      - name: tmp
        emptyDir: {}
    extraVolumeMounts:
      - name: tmp
        mountPath: /tmp
