---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immichframe
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immichframe
  dataFrom:
    - extract:
        key: immichframe
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immichframe-keys
spec:
  refreshInterval: "8760h"
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immichframe-keys
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password10
      rewrite:
        - regexp:
            source: "password"
            target: "AuthenticationSecret"
