---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-photos
  finalizers:
    - cluster.local/data-protection
spec:
  capacity:
    storage: 246Ti
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  local:
    path: /var/mnt/reservoir/photos
  mountOptions:
    - noatime
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kantai1
