---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: default-photos
spec:
  capacity:
    storage: 246Ti
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: zfs-static
  mountOptions:
    - noatime
  csi:
    driver: zfs-static-csi.jfroy.github.com
    volumeHandle: reservoir/photos
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - kantai1
