---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photos
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: zfs-static
  volumeMode: Filesystem
  volumeName: default-photos
