{
 "title": "Cluster / Global performance",
 "description": "This Grafana dashboard offers a detailed overview of Kubernetes cluster performance and resource usage. It features time series graphs that monitor various metrics, including the number of namespaces, running pods, RAM usage, CPU usage and other key Kubernetes resources such as services, endpoints, and deployments. The dashboard also tracks persistent volume usage both as a percentage and in gigabytes, providing insights into storage utilization. Additionally, it visualizes network usage, covering both bytes and packets per second for incoming and outgoing traffic.",
 "tags": [
  "Custom",
  "Global"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   { "name": "resolution", "query": "1m, 3m, 5m" }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Global CPU  Usage",
   "type": "bargauge",
   "description": "This panel provides a general visualization of global CPU usage in a Kubernetes cluster. Through a bar gauge, it represents the current state of CPU utilization.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", cluster=\"$cluster\"}[$resolution])))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", cluster=\"$cluster\"}) / sum(machine_cpu_cores{cluster=\"$cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\"}) / sum(machine_cpu_cores{cluster=\"$cluster\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Cluster CPU Utilization",
   "type": "timeseries",
   "description": "This panel displays a time series visualization of CPU utilization across a Kubernetes cluster. It provides a smooth, continuous line graph representing the average CPU usage over time, with color-coded thresholds to indicate varying levels of utilization.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(sum by (instance, cpu) (rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", cluster=\"$cluster\"}[$resolution])))",
     "legendFormat": "CPU usage in %"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "description": "This panel provides an overview of CPU usage in a Kubernetes cluster. Displayed as a stat panel, it presents the most recent data on CPU consumption, including real-time usage, resource requests, and limits, as well as the total available CPU cores in the cluster.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!~\"idle|iowait|steal\", cluster=\"$cluster\"}[$resolution]))",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\", cluster=\"$cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"cpu\", cluster=\"$cluster\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_cpu_cores{cluster=\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Global RAM Usage",
   "type": "bargauge",
   "description": "This panel provides a general visualization of global RAM usage in a Kubernetes cluster. Through a bar gauge, it represents the current state of RAM utilization.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\"} - node_memory_MemAvailable_bytes{cluster=\"$cluster\"}) / sum(node_memory_MemTotal_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\"}) / sum(machine_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\"}) / sum(machine_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Cluster Memory Utilization",
   "type": "timeseries",
   "description": "This panel displays a time series visualization of RAM utilization across a Kubernetes cluster. It provides a smooth, continuous line graph representing the average RAM usage over time, with color-coded thresholds to indicate varying levels of utilization.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\"} - node_memory_MemAvailable_bytes{cluster=\"$cluster\"}) / sum(node_memory_MemTotal_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Memory usage in %"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "stat",
   "description": "This panel provides an overview of RAM usage in a Kubernetes cluster. Displayed as a stat panel, it presents the most recent data on CPU consumption, including real-time usage, resource requests, and limits, as well as the total available RAM cores in the cluster.",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{cluster=\"$cluster\"} - node_memory_MemAvailable_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Real"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\", cluster=\"$cluster\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{resource=\"memory\", cluster=\"$cluster\"})",
     "legendFormat": "Limits"
    },
    {
     "expr": "sum(machine_memory_bytes{cluster=\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Nodes count",
   "type": "timeseries",
   "description": "This panel presents a time series visualization of the node count within a Kubernetes cluster. It displays the number of nodes over time, offering a smooth line graph with color-coded thresholds to highlight significant changes.",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "count(count by (node) (kube_node_info{cluster=\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Namespaces count",
   "type": "timeseries",
   "description": "This panel provides a time series visualization of the number of namespaces in a Kubernetes cluster. Displayed as a smooth line graph, it tracks the total count of namespaces over time, allowing users to monitor changes in namespace creation.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "targets": [
    {
     "expr": "count(kube_namespace_created{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Running Pods count",
   "type": "timeseries",
   "description": "This panel visualizes the count of running pods in a Kubernetes cluster over time. The data is presented as a smooth line graph, allowing users to monitor fluctuations in the number of active pods.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Kubernetes Resource Count",
   "type": "timeseries",
   "description": "This panel provides a comprehensive time series view of various Kubernetes resource counts. It tracks and visualizes the number of namespaces, running containers, running pods, services, endpoints, ingresses, deployments, statefulsets, daemonsets, persistent volume claims, horizontal pod autoscalers, configmaps, secrets, network policies, and nodes over time.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_namespace_labels{cluster=\"$cluster\"})",
     "legendFormat": "Namespaces"
    },
    {
     "expr": "sum(kube_pod_container_status_running{cluster=\"$cluster\"})",
     "legendFormat": "Running Containers"
    },
    {
     "expr": "sum(kube_pod_status_phase{phase=\"Running\", cluster=\"$cluster\"})",
     "legendFormat": "Running Pods"
    },
    {
     "expr": "sum(kube_service_info{cluster=\"$cluster\"})",
     "legendFormat": "Services"
    },
    {
     "expr": "sum(kube_endpoint_info{cluster=\"$cluster\"})",
     "legendFormat": "Endpoints"
    },
    {
     "expr": "sum(kube_ingress_info{cluster=\"$cluster\"})",
     "legendFormat": "Ingresses"
    },
    {
     "expr": "sum(kube_deployment_labels{cluster=\"$cluster\"})",
     "legendFormat": "Deployments"
    },
    {
     "expr": "sum(kube_statefulset_labels{cluster=\"$cluster\"})",
     "legendFormat": "Statefulsets"
    },
    {
     "expr": "sum(kube_daemonset_labels{cluster=\"$cluster\"})",
     "legendFormat": "Daemonsets"
    },
    {
     "expr": "sum(kube_persistentvolumeclaim_info{cluster=\"$cluster\"})",
     "legendFormat": "Persistent Volume Claims"
    },
    {
     "expr": "sum(kube_hpa_labels{cluster=\"$cluster\"})",
     "legendFormat": "Horizontal Pod Autoscalers"
    },
    {
     "expr": "sum(kube_configmap_info{cluster=\"$cluster\"})",
     "legendFormat": "Configmaps"
    },
    {
     "expr": "sum(kube_secret_info{cluster=\"$cluster\"})",
     "legendFormat": "Secrets"
    },
    {
     "expr": "sum(kube_networkpolicy_labels{cluster=\"$cluster\"})",
     "legendFormat": "Network Policies"
    },
    {
     "expr": "count(count by (node) (kube_node_info{cluster=\"$cluster\"}))",
     "legendFormat": "Nodes"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Persistent Volumes - Usage in %",
   "type": "timeseries",
   "description": "This Grafana panel visualizes the usage percentage of persistent volumes in a Kubernetes cluster. It displays the ratio of used bytes to total capacity for each persistent volume claim (PVC) over time. The color scheme and threshold settings highlight high usage, with values above 80% turning red.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{cluster=\"$cluster\"}) by (persistentvolumeclaim) / sum(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\"}) by (persistentvolumeclaim)",
     "legendFormat": "{{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "Persistent Volumes - Usage in GB",
   "type": "table",
   "description": "This panel is a table displaying persistent volume usage in your Kubernetes cluster. It features two columns for each Persistent Volume Claim (PVC): \"Used,\" indicating the total storage used in bytes, and \"Total,\" showing the total capacity in bytes.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kubelet_volume_stats_used_bytes{cluster=\"$cluster\"}) by (persistentvolumeclaim)"
    },
    {
     "expr": "sum(kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\"}) by (persistentvolumeclaim)"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Network usage (bytes)",
   "type": "timeseries",
   "description": "This panel displays network usage in bytes over time for a Kubernetes cluster. It features a time series graph with two lines: one representing incoming network traffic (\"In\") and the other for outgoing network traffic (\"Out\"). ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{cluster=\"$cluster\"}[$resolution]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(node_network_transmit_bytes_total{instance=\"$instance\", cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Network usage (packet/s)",
   "type": "timeseries",
   "description": "This panel shows network usage in packets per second over time for a Kubernetes cluster. It features a time series graph with two lines: one for incoming network packets (\"In\") and another for outgoing network packets (\"Out\").",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_packets_total{cluster=\"$cluster\"}[$resolution]))",
     "legendFormat": "In"
    },
    {
     "expr": "- sum(rate(node_network_transmit_packets_total{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "Out"
    }
   ]
  }
 ]
}