{
 "title": "ZFS",
 "description": "A ZFS dashboard with simple metrics including capacity, pool activity, IO size, latency and etc.",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(zpool_stats_size, instance)"
    }
   },
   {
    "name": "pool",
    "query": {
     "query": "label_values(zpool_stats_size{instance=\"$instance\", vdev=\"root\"}, name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$pool",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zpool_stats_free{instance=\"$instance\",name=~\"$pool\",vdev=~\"root\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Capacity ($pool)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(zpool_stats_alloc{instance=\"$instance\",name=~\"$pool\",vdev=~\"root\"} /\r\nzpool_stats_size{instance=\"$instance\",name=~\"$pool\",vdev=~\"root\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pool Activity ($pool)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(zpool_stats_read_bytes{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval])) without (state)",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "sum(rate(zpool_stats_write_bytes{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval]))",
     "legendFormat": "Write Bytes"
    },
    {
     "expr": "sum(rate(zpool_stats_read_ops{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval])) without (state)",
     "legendFormat": "Read Ops"
    },
    {
     "expr": "sum(rate(zpool_stats_write_ops{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval])) without (state)",
     "legendFormat": "Write Ops"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zpool_stats_read_errors{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}",
     "legendFormat": "Read Errors"
    },
    {
     "expr": "zpool_stats_write_errors{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}",
     "legendFormat": "Write Errors"
    },
    {
     "expr": "zpool_stats_checksum_errors{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}",
     "legendFormat": "Checksum Errors"
    },
    {
     "expr": "zpool_stats_fragmentation{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}",
     "legendFormat": "Fragmentation"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zpool_stats_alloc{instance=\"$instance\",name=~\"$pool\",vdev=~\"root\"}",
     "legendFormat": "Alloc"
    },
    {
     "expr": "zpool_stats_free{instance=\"$instance\",name=~\"$pool\",vdev=~\"root\"}",
     "legendFormat": "Free"
    },
    {
     "expr": "zpool_stats_size{instance=\"$instance\",name=~\"$pool\",vdev=~\"root\"}",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "I/O Active Queue ($pool)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(zpool_vdev_stats_async_r_active_queue{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval]))",
     "legendFormat": "Async Read"
    },
    {
     "expr": "sum(rate(zpool_vdev_stats_async_w_active_queue{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval]))",
     "legendFormat": "Async Write"
    },
    {
     "expr": "sum(rate(zpool_vdev_stats_sync_r_active_queue{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval]))",
     "legendFormat": "Sync Read"
    },
    {
     "expr": "sum(rate(zpool_vdev_stats_sync_w_active_queue{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval]))",
     "legendFormat": "Sync Write"
    },
    {
     "expr": "sum(rate(zpool_vdev_stats_async_scrub_active_queue{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval]))",
     "legendFormat": "Async Scrub"
    }
   ]
  },
  {
   "title": "I/O Pending Queue ($pool)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(zpool_vdev_stats_async_r_pend_queue{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval]))",
     "legendFormat": "Async Read"
    },
    {
     "expr": "sum(rate(zpool_vdev_stats_async_w_pend_queue{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval]))",
     "legendFormat": "Async Write"
    },
    {
     "expr": "sum(rate(zpool_vdev_stats_sync_r_pend_queue{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval]))",
     "legendFormat": "Sync Read"
    },
    {
     "expr": "sum(rate(zpool_vdev_stats_sync_w_pend_queue{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval]))",
     "legendFormat": "Sync Write"
    },
    {
     "expr": "sum(rate(zpool_vdev_stats_async_scrub_pend_queue{instance=\"$instance\",name=~\"$pool\",vdev=\"root\"}[$__rate_interval]))",
     "legendFormat": "Async Scrub"
    }
   ]
  },
  {
   "title": "Volume",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Volume",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "zpool_stats_fragmentation{instance=\"$instance\",name=~\"$pool\",vdev!=\"root\",path!=\"\"}",
     "legendFormat": "Fragmentation"
    },
    {
     "expr": "zpool_stats_checksum_errors{instance=\"$instance\",name=~\"$pool\",vdev!=\"root\",path!=\"\"}",
     "legendFormat": "Checksum errors"
    },
    {
     "expr": "zpool_stats_read_errors{instance=\"$instance\",name=~\"$pool\",vdev!=\"root\",path!=\"\"}",
     "legendFormat": "read errors"
    },
    {
     "expr": "zpool_stats_write_errors{instance=\"$instance\",name=~\"$pool\",vdev!=\"root\",path!=\"\"}",
     "legendFormat": "write errors"
    }
   ]
  },
  {
   "title": "Scan",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Finished",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zpool_scan_stats_start_ts{instance=\"$instance\",name=~\"$pool\",state=\"finished\"} * 1000",
     "legendFormat": "start time"
    },
    {
     "expr": "zpool_scan_stats_end_ts{instance=\"$instance\",name=~\"$pool\",state=\"finished\"} * 1000",
     "legendFormat": "end time"
    },
    {
     "expr": "zpool_scan_stats_examined{instance=\"$instance\",name=~\"$pool\",state=\"finished\"}",
     "legendFormat": "scaned"
    },
    {
     "expr": "zpool_scan_stats_processed{instance=\"$instance\",name=~\"$pool\",state=\"finished\"}",
     "legendFormat": "repaired"
    },
    {
     "expr": "zpool_scan_stats_errors{instance=\"$instance\",name=~\"$pool\",state=\"finished\"}",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Ongoing",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "zpool_scan_stats_start_ts{instance=\"$instance\",name=~\"$pool\",state!=\"finished\"} * 1000",
     "legendFormat": "start time"
    },
    {
     "expr": "zpool_scan_stats_rate{instance=\"$instance\",name=~\"$pool\",state!=\"finished\"}",
     "legendFormat": "rate"
    },
    {
     "expr": "zpool_scan_stats_errors{instance=\"$instance\",name=~\"$pool\",state!=\"finished\"}",
     "legendFormat": "errors"
    },
    {
     "expr": "zpool_scan_stats_to_examine{instance=\"$instance\",name=~\"$pool\",state!=\"finished\"}",
     "legendFormat": "to scan"
    },
    {
     "expr": "zpool_scan_stats_to_process{instance=\"$instance\",name=~\"$pool\",state!=\"finished\"}",
     "legendFormat": "to repair"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "zpool_scan_stats_rate{instance=\"$instance\",name=~\"$pool\",state!=\"finished\"}",
     "legendFormat": "{{ name }} - {{ function }}"
    }
   ]
  },
  {
   "title": "IO size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Sync Read",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "targets": [
      {
       "expr": "sum by (le)(rate(zpool_io_size_sync_read_ind{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Sync Write",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "targets": [
      {
       "expr": "sum by (le)(rate(zpool_io_size_sync_write_ind{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Async Read",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "targets": [
      {
       "expr": "sum by (le)(rate(zpool_io_size_async_read_ind{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Async Write",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
     "targets": [
      {
       "expr": "sum by (le)(rate(zpool_io_size_async_write_ind{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Scrub",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
     "targets": [
      {
       "expr": "sum by (le)(rate(zpool_io_size_scrub_read_ind{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Trim",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
     "targets": [
      {
       "expr": "sum by (le)(rate(zpool_io_size_trim_write_ind{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Read Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "sum by (le)(rate(zpool_latency_total_read{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval]))",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Total Write Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "targets": [
      {
       "expr": "sum by (le)(rate(zpool_latency_total_write{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Disk Read Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 89 },
     "targets": [
      {
       "expr": "sum by (le)(rate(zpool_latency_disk_read{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval]))",
       "legendFormat": "{{ pool }}"
      }
     ]
    },
    {
     "title": "Disk Write Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 89 },
     "targets": [
      {
       "expr": "sum by (le)(rate(zpool_latency_disk_write{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Sync Read Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
     "targets": [
      {
       "expr": "sum by (le) (rate(zpool_latency_sync_read{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Sync Write Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
     "targets": [
      {
       "expr": "sum by (le)(rate(zpool_latency_sync_write{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Async Read Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
     "targets": [
      {
       "expr": "sum by (le) (rate(zpool_latency_async_read{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Async Write Latency",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
     "targets": [
      {
       "expr": "sum by (le)(rate(zpool_latency_async_write{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Scrub",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
     "targets": [
      {
       "expr": "sum by (le) (rate(zpool_latency_scrub{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Trim",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
     "targets": [
      {
       "expr": "sum by (le)(rate(zpool_latency_trim{instance=\"$instance\",name=\"$pool\",vdev=\"root\"}[$__rate_interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  }
 ]
}