---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: konflate
spec:
  refreshPolicy: OnChange
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: konflate
  data:
    - secretKey: KONFLATE_APP_CLIENT_ID
      remoteRef:
        key: github-jfroy-bot/github_app_client_id
    - secretKey: KONFLATE_APP_PRIVATE_KEY
      remoteRef:
        key: github-jfroy-bot/github_app_private_key
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: password32
      rewrite:
        - regexp:
            source: "password"
            target: "KONFLATE_WEBHOOK_SECRET"
