---
# yaml-language-server: $schema=https://crd.kantai.xyz/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-pet-tagger
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: immich-pet-tagger
  data:
    - secretKey: IMMICH_API_KEY
      remoteRef:
        key: immich-pet-tagger/credential
