---
# yaml-language-server: $schema=https://crd.kantai.xyz/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: external-secrets
  values:
    certController:
      podDisruptionBudget:
        enabled: false
    extendedMetricLabels: true
    grafanaDashboard:
      enabled: true
    livenessProbe:
      enabled: true
    podDisruptionBudget:
      enabled: false
    serviceMonitor:
      enabled: true
      interval: 1m
      metricRelabelings:
        - action: drop
          sourceLabels: ["__name__"]
          regex: workqueue_(work|queue)_duration_seconds_bucket
        - action: drop
          sourceLabels: ["__name__"]
          regex: controller_runtime_reconcile_time_seconds_bucket
    # Webhook crashloops when Cert-Manager is used with default values
    # https://github.com/external-secrets/external-secrets/issues/2519
    webhook:
      certManager:
        enabled: true
        cert:
          issuerRef:
            name: cluster-ca
            kind: ClusterIssuer
            group: cert-manager.io
          duration: 2160h # 90d
      lookaheadInterval: 240h # 10d
      podDisruptionBudget:
        enabled: false
